Fixes grammar/typos
gorilla-devs/ferium pull request #216
Opened 2022-10-13 23:29 UTC by nikoandpiko

Updates readme with grammar and typo fixes.

2022-10-13 23:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gorilla-devs/ferium?pullRequest=216) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gorilla-devs/ferium?pullRequest=216) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gorilla-devs/ferium?pullRequest=216) it.</sub>

2022-10-13 23:34 UTC, AshtakaOOf commented
Peoples making fork to correct typo are the real chad, out here in the harsh world of Github land.

2022-10-14 14:37 UTC, theRookieCoder requested changes

2022-10-15 01:19 UTC, nikoandpiko commented on README.md
> -You can run clippy lints using `just lint`, integration tests using `cargo test`, and delete all the build and test artefacts using `just clean`.
Did not know that. I updated the British spellings.

2022-10-15 11:20 UTC, theRookieCoder approved these changes

2022-10-15 11:21 UTC, merged