Add hide donation message option in add subcommand
gorilla-devs/ferium pull request #400
Opened 2024-01-31 16:38 UTC by atamakahere-git

Enhancement for #369

2024-04-07 20:12 UTC, dr-vortex commented
@atamakahere-git Any updates on this?

2024-05-21 18:53 UTC, theRookieCoder requested changes

2024-05-21 18:53 UTC, theRookieCoder commented on src/cli.rs
> +        #[clap(long, short = 'H', alias = "hide-donation-message")]
The alias here is unnecessary, clap will automatically convert Rust snake_case variables and PascalCase subcommands to the standard kebab-case used in CLIs.

```diff
- #[clap(long, short = 'H', alias = "hide-donation-message")]
+ #[clap(long, short = 'H')]
```

2024-05-21 18:55 UTC, theRookieCoder commented on src/cli.rs
> +        #[clap(long, short = 'H', alias = "hide-donation-message")]
Also I think `Hide the donation message` is good for the description too

2024-06-11 13:22 UTC, theRookieCoder commented
Donation messages would've been quite difficult to deal with when adding multiple mods, so I ended up removing them entirely.

2024-06-11 13:22 UTC, closed without merging